# Generated by Django 5.0.3 on 2024-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefirmapp', '0004_dispatch_child_dispatch_parent_inward_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_child',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inward_child',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
