# Generated by Django 5.0.3 on 2024-03-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefirmapp', '0006_alter_inward_child_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_child',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_opening_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
