# Generated by Django 5.0.3 on 2024-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefirmapp', '0007_alter_dispatch_child_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_gst_percent',
            field=models.IntegerField(),
        ),
    ]
