# Generated by Django 5.0.3 on 2024-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradefirmapp', '0008_alter_item_item_gst_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_child',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inward_child',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_gst_percent',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_opening_balance',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='order_child',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
