# Generated by Django 5.0.3 on 2024-03-31 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradefirmapp', '0010_alter_dispatch_child_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Dispatch_Child',
        ),
        migrations.DeleteModel(
            name='Dispatch_Parent',
        ),
        migrations.DeleteModel(
            name='Inward_Child',
        ),
        migrations.DeleteModel(
            name='Inward_Parent',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order_Child',
        ),
        migrations.DeleteModel(
            name='Order_Parent',
        ),
    ]
