# Generated by Django 5.0.3 on 2024-04-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tradefirmapp', '0011_delete_client_delete_dispatch_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('client_gstn', models.CharField(max_length=15)),
                ('remark', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(max_length=25)),
                ('dispatc_date', models.DateField()),
                ('item_id', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('remark', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch_Parent',
            fields=[
                ('dispatch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=25)),
                ('remark', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inward_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_id', models.CharField(max_length=25)),
                ('item_id', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('remark', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inward_Parent',
            fields=[
                ('inward_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inward_date', models.DateField()),
                ('remark', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_unit', models.CharField(max_length=20)),
                ('item_opening_balance', models.IntegerField()),
                ('item_hsn', models.CharField(max_length=10)),
                ('item_gst_percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25)),
                ('item_id', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('remark', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Parent',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('client_id', models.CharField(max_length=25)),
                ('ordered_via', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
